name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: xieyubo/cppmatrix-buildcontainer:ubuntu24.04-cuda12.8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          PATH=/usr/local/cuda-12.8/bin:$PATH CXX=clang++ cmake .. -GNinja
          ninja

      - name: Test
        run: |
          cd build
          ctest