name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  build_and_test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    container:
      image: cppmatrix/buildcontainer:ubuntu24.04-cuda12.8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          CXX=clang++ cmake .. -GNinja
          ninja

      - name: Test
        run: |
          cd build
          ctest
      
      - name: Build doc
        run: |
          cd build
          ninja doc

      - name: Publish doc
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.WEBSITE_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: build/doxygen/html
          skip_app_build: true
          skip_api_build: true
          output_location: build/doxygen/html
  
  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.WEBSITE_DEPLOY_TOKEN }}
          action: "close"